### ISSUE TITLE
variables.sqf

### ISSUE THREAD

**Issue by ZizionarD** [AirwavesMan/custom-epoch-functions#1]
Hello! As I understand it, the dayz_resetSelfActions array should be left completely in the custom file, or you can only leave the ones that I added from the scripts?

**Comment by AirwavesMan** [comment]
If you have to add a resetAction from the fn_selfactions then you have to carry over the whole dayz_resetSelfActions from the core epoch variables to your custom variables and add your new resetAction at the end of the dayz_resetSelfActions array then.
Example from the modPack: https://github.com/oiad/modPack/blob/master/DayZ_Epoch_11.Chernarus/dayz_code/init/variables.sqf

**Comment by ZizionarD** [comment]
> If you have to add a resetAction from the fn_selfactions then you have to carry over the whole dayz_resetSelfActions from the core epoch variables to your custom variables and add your new resetAction at the end of the dayz_resetSelfActions array then.
> Example from the modPack: https://github.com/oiad/modPack/blob/master/DayZ_Epoch_11.Chernarus/dayz_code/init/variables.sqf

In fact, I logically did so) Thank you)
